#!/bin/bash
## xs_patcher
## downloads XenServer patches to be cached in a local server

function download_patches {
		rm -rf /tmp/xs_patcher_tmp/
		mkdir -p /tmp/xs_patcher_tmp
		echo "Looking for missing patches on $HOSTNAME for $DISTRO..."

		for PATCH in `cat patches/$DISTRO`
		do
				PATCH_NAME=`echo $PATCH | awk -F'|' {'print $1'}`
				PATCH_UUID=`echo $PATCH | awk -F'|' {'print $2'}`
				PATCH_URL=`echo $PATCH | awk -F'|' {'print $3'}`
				PATCH_KB=`echo $PATCH | awk -F'|' {'print $4'}`

				if [ ! -f cache/$PATCH_NAME.xsupdate ]
				then
					echo "Downloading from $PATCH_URL..."
					wget -q $PATCH_URL -P /tmp/xs_patcher_tmp/
					unzip -qq /tmp/xs_patcher_tmp/$PATCH_NAME.zip -d cache/
					rm -f /tmp/xs_patcher_tmp/$PATCH_NAME.zip
					echo "Downloaded $PATCH_NAME... [ Release Notes @ $PATCH_KB ]"
				fi
		done
		rm -rf /tmp/xs_patcher_tmp/
		echo "Download complete"
}

#"XenServer release 6.0.0"
#DISTRO="boston"
#"XenServer release 6.0.2"
#DISTRO="sanibel"
#"XenServer release 6.1.0"
#DISTRO="tampa"
#"XenServer release 6.2.0"
#DISTRO="clearwater"

for DISTRO in "clearwater"
	do
	download_patches
done